#!/usr/bin/env bash

_command_exists() {
    type "$1" &> /dev/null
}

if [[ -z $_shims_sourced ]]; then

    DIR="$HOME/.dotbare"
    [[ -d "$DIR" ]] &&  ! _command_exists dotbare && source $DIR/dotbare.plugin.zsh

    [[ _command_exists direnv ]] && eval "$(direnv hook bash)"

    if _command_exists goenv ||
        [[ -n "$GOENV_ROOT" && -x "$GOENV_ROOT/bin/goenv" ]] ||
        [[ -x "$HOME/.goenv/bin/goenv" ]]; then
        true
    else
        # Set GOENV_ROOT, if not already set
        export GOENV_ROOT="${GOENV_ROOT:-$HOME/.goenv}"

        # Add GOENV_ROOT/bin to PATH, if that's where it's installed
        ! _command_exists goenv && [[ -x "$GOENV_ROOT/bin/goenv" ]] && _path_prepend "$GOENV_ROOT/bin"

        # Initialize goenv
        eval "$(goenv init - bash)"
    fi


fi

export _shims_sourced=1
