#!/usr/bin/env bash

_command_exists() {
    type "$1" &> /dev/null
}

SHELL=$(echo $0)

[[ -d ""$HOME/.dotbare"" ]] && ! _command_exists dotbare && source "$HOME/.dotbare"/dotbare.plugin.zsh

_command_exists direnv && eval "$(direnv hook $SHELL)"

if [[ -n "$GOENV_ROOT" && -x "$GOENV_ROOT/bin/goenv" ]] || [[ -x "$HOME/.goenv/bin/goenv" ]]; then
    if ! _command_exists goenv; then
        # Set GOENV_ROOT, if not already set
        export GOENV_ROOT="${GOENV_ROOT:-$HOME/.goenv}"

        # Add GOENV_ROOT/bin to PATH, if that's where it's installed
        ! _command_exists goenv && [[ -x "$GOENV_ROOT/bin/goenv" ]] && _path_prepend "$GOENV_ROOT/bin"

        # Initialize goenv
        eval "$(goenv init - $SHELL)"
    fi
fi

if [[ -n "$JENV_ROOT" && -x "$JENV_ROOT/bin/jenv" ]] || [[ -x "$HOME/.jenv/bin/jenv" ]]; then
    if ! _command_exists jenv; then
        # Set JENV_ROOT, if not already set
        export JENV_ROOT="${JENV_ROOT:-$HOME/.jenv}"

        # Add JENV_ROOT/bin to PATH, if that's where it's installed
        ! _command_exists jenv && [[ -x "$JENV_ROOT/bin/jenv" ]] && _path_prepend "$JENV_ROOT/bin"

        # Initialize jenv
        eval "$(jenv init - $SHELL)"
    fi
fi

if [[ -d $HOME/.nodenv ]]; then
    if ! _command_exists nodenv; then
        export NODENV_ROOT="$HOME/.nodenv"
        _path_prepend "$NODENV_ROOT/bin"
        eval "$(nodenv init - $SHELL)"
    fi
fi

set -x
if [[ -n "$PYENV_ROOT" && -x "$PYENV_ROOT/bin/pyenv" ]] || [[ -x "$HOME/.pyenv/bin/pyenv" ]]; then
    if ! _command_exists pyenv; then
        export PYENV_ROOT="${PYENV_ROOT:-$HOME/.pyenv}"
        _path_prepend "$PYENV_ROOT/bin"
        eval "$(pyenv init -)"
    fi
fi
set +x
